### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Homepage

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#41]
Er moet een speciale weergave komen voor de homepage. De bedoeling is dat hierop verschillende blokken komen met bijvoorbeeld:
- [x] Wat is Joomla!?
- [x] Laatste nieuwsberichten
- [x] Laatste forum berichten
- [ ] Opvallende Joomla! sites
- [ ] Testimonials (zie #5)

Ik denk dat het handigste is om dat met behulp van modules te regelen. Wat er momenteel staat is nog dummy tekst, maar de opzet is wel leuk en kan gebruikt worden!

**Comment by hans2103** [comment]
@n9iels ik heb de homepage dynamisch gemaakt middels issue #71 
Maar heb nog een vraag in issue #73 
Zou jij me uitleg kunnen geven over de gestelde vraag?

**Comment by conconnl** [comment]
Fase 1 is klaar.
Fase 2 issues zijn aanwezig
