### ISSUE TITLE
[Development] - Download Page Lay-Out

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#60]
@n9iels 
Als besproken hierbij het verzoek om de [download (nu taalpakketten)](http://nieuw.joomlacommunity.eu/taalpakketten) pagina template override zo aan te passen dat deze meer niveaus toont i.p.v. alleen de eerste.
We hebben 2 eerste niveaus "Joomla" & "Extensies", deze hoofmappen bevatten nieuwe mappen en downloads, deze moeten op de pagina onder de hoofdtitel getoond worden.

Acties:
- [x] Bestanden tonen in het overzicht onder de Hoofdmap (zie screenshot) met een eigen class voor stijl mogelijkheden. (Dus onder Joomla de 1e niveau inhoud van de map tonen)
- [x] Sub-Mappen tonen in het overzicht onder de Hoofdmap  met een eigen class voor stijl mogelijkheden.
- [x] Hoofdmap (titel) niet klikbaar hebben.

**To-Do**
- [x] Unieke classes toevoegen voor specifieke styling
- [x] Een menu item die alle items uit een map laat zien werkt nog niet goed. Deze laat enkel de mapnamen zien maar geen inhoud van de mappen

Als er meer acties nodig zijn zal ik het aanvullen.

<img width="1190" alt="screen shot 2016-04-16 at 17 10 35" src="https://cloud.githubusercontent.com/assets/11913918/14767884/c073c592-0a31-11e6-9462-dffd522265e9.png">

**Comment by n9iels** [comment]
Ik heb een erg goed begin gemaakt aan de download pagina. Momenteel staat deze nog in de branch _download-page_ omdat ik nog een paar laatste puntjes op de i wil zetten.

Hieronder wat screenshots hoever het nu is:
**Overzicht**
![schermafdruk van 2016-08-01 17-03-52](https://cloud.githubusercontent.com/assets/2659866/17298449/67736390-580a-11e6-8376-b8b04d45ebce.png)

**Losse bestanden binnen een map**
![schermafdruk van 2016-08-01 17-04-06](https://cloud.githubusercontent.com/assets/2659866/17298455/70d96452-580a-11e6-9ddb-91b62aa06fb2.png)

**Weergave van een map met twee sub-mappen**
![schermafdruk van 2016-08-01 17-04-17](https://cloud.githubusercontent.com/assets/2659866/17298513/869f6cd2-580a-11e6-8a6f-abbe3d1fc065.png)

**Detail weergave van een download**
![schermafdruk van 2016-08-01 17-04-28](https://cloud.githubusercontent.com/assets/2659866/17298522/8e24874e-580a-11e6-8df3-8850b80ac2e8.png)

Ik vind zelf de weergaven van losse bestanden in een map nog niet zo mooi.
Mocht iemand op en/of aanmerkingen hebben hoor ik het uiteraard graag! Ook zou het handig zijn als mensen die wel grafisch aangelegd zijn ernaar kijken :P

**Comment by n9iels** [comment]
Ik heb de download pagina toegevoegd aan de develop branch, zie commits:
- b401fe3f9c79fbb2579ce51c324de93fac571c05
- f79c3225852c05f9874d0e35593455a0b9167e7a

**Layout**
Zie screen shots hierboven, deze zijn up-to-do

**Download folder**
Alle downloads staan in de folder `rsdownloads`, deze naam is gekozen omdat het vrij aannemelijk is dat het menu item met de alias `downloads` wel eens aangemaakt zou kunnen worden.

De map kan op vrijwel elke manier worden ingericht. Indien er een map wordt geplaatst zal deze map als panel worden getoond met daaronder de inhoud. Losse bestanden in een map zullen in een apart pannel getoond worden.
Als de map enkel losse bestanden heeft wordt elk bestand apart getoond.

**Classes voor styling**
De pannels bevatten de volgende class `panel-mapnaam`. Op deze manier kan een specifiek pannel gestyled worden.

**Comment by conconnl** [comment]
@n9iels 
Ik heb een error gevonden.
Deze krijg ik als ik vanuit de pagina Extensies, op een van de zichtbare extensies klik.
![2016-08-10 00_15_53-extensies](https://cloud.githubusercontent.com/assets/11913918/17535668/4bf0151e-5e90-11e6-85db-961a604a3603.png)

**Comment by n9iels** [comment]
Heeft ermee temaken dat de download map op mijn PC en de server verschilt. Het bestand staat wel in de database maar niet in de download map.

Als je in de backend kijkt zal je dat als het goed is zien :)

**Comment by conconnl** [comment]
Dat zou op gaan als ik niet eerst via de live site een bestand geupload had.
Het bestand Joomla Patch heb ik geplaatst via de site en krijg dezelfde foutmelding.

**Comment by hans2103** [comment]
Ik heb zojuist via #102 .gitignore aangepast en de inhoud van de map rsdownloads uitgesloten van de repo.

**Comment by n9iels** [comment]
@conconnl ik heb zojuist via de back-end van de live website een bestand geupload in de Joomla! map (3.6.2 taalpakket) en kan hem nu zonder problemen aanklikken en bereiken.

@hans2103 Goede zet! Had hem er nog niet in gezet omdat ik wat test data wou voor de live site :)

**Comment by conconnl** [comment]
@n9iels 
Het werkt nog steeds niet.
Je hebt het over de map Joomla, terwijl ik in de tekst en in de screenshot de map extensies laat zien.

Heb zojuist alles van Regular Labs opnieuw aangemaakt en hierna werkt het nog niet.
Kijk maar via deze link: http://nieuw.joomlacommunity.eu/taalpakketten/extensies
Ik kan nog alles verwijderen en opnieuw aanmaken in de site als test, maar daarna houd het voor mij op als het nog niet werkt.

**Comment by n9iels** [comment]
oww nu snap ik hem. Ga ik naar kijken :+1:

**Comment by conconnl** [comment]
@n9iels heb je hier nog verder na kunnen kijken, of kun je dit 10 september doen?

**Comment by n9iels** [comment]
@conconnl ik heb hier nog geen oplossing voor kunnen vinden. Het probleem zit hem erin dat het pad naar locatie van het bestand niet goed word gerekend. Op het moment dat je vanaf de hoofd categorie navigeert gaat het goed. Klik je een menu item aan dat start bij een subcategorie klopt het pad niet meer.

Als iemand suggesties heeft graag :)

**Comment by jissereitsma** [comment]
Bij het opzetten van een lokale versie kreeg ik meteen foutmeldingen in de RSFiles backend dat het download map niet gevonden kon worden. Ik heb daarna de RSFiles Settings aangepast zoals ik nu in de wiki heb omschreven (https://github.com/stichtingsympathy/joomlacommunity.nl/wiki/Aan-de-slag-met-GitHub, zie onderin). Daarna is de fout opgelost bij mij. De URLs zoals in deze thread omschreven leveren nul problemen op. Kan het zijn dat dit dus ook op de nieuw.joomlacommunity.eu site aangepast moet worden?

**Comment by conconnl** [comment]
@jissereitsma ik heb de setting aangepast, maar ik blijf de melding krijgen bestand niet gevonden.
http://nieuw.joomlacommunity.eu/taalpakketten/extensies

Klik dan maar bijvoorbeeld op Helix.

**Comment by jissereitsma** [comment]
En kan je checken of bijvoorbeeld het bestand `rsdownloads/extensies/jce/jce_editor_plugin.zip` op de nieuw.joomlacommunity.eu site staat (FTP)?

**Comment by n9iels** [comment]
@jissereitsma het punt zit hem in het menu. Je gaat naar downloads en dan via het submenu naar bijv. Extensies.

Daar gaat het vervolgens fout bij bepaalde links.

**Comment by conconnl** [comment]
Precies.
Dus naar taalpakketten en daarna naar JCE werkt goed.
Naar SubMenu Extensies en dan naar JCE Editor of plugin gaat fout.

**Comment by n9iels** [comment]
Ik heb hier nog steeds geen oplossing voor kunnen vinden helaas :-(

**Comment by sanderpotjer** [comment]
Extensie is vervangen voor DOCman en verder opgemaakt.
